- name: Create the 'admin' group
  group: name=admin state=present

- name: Create the 'aeon' group
  group: name=aeon state=present

- name: Create 'aeon' user
  user:
    name: aeon
    state: present
    system: yes
    createhome: no

- name: Add 'admin' user
  user:
    name: admin
    state: present
    groups: users
    shell: /bin/bash
    password:
        $6$rounds=656000$2jNVVCliDs5XvmZs$eZ4F0WO6d6w5cBoMZ341hbuknOjx3ObhPHcgSR0D76gICz/Cc9IzXcPGaWzMdpiT7Cp.sflfiPhRDROvNH0eF/

- name: add 'admin' to sudoers
  copy: src=sudoer-admin dest=/etc/sudoers.d/admin mode=440
