# --------------------------------------------------------
- include_vars: "{{ playbook_dir }}/vars/dhcp-server.yml"

- name: install ISC DHCP server
  apt: name=isc-dhcp-server state=present

- name: install DHCP configuration file
  template: src=dhcpd.conf dest=/etc/dhcp/dhcpd.conf

- name: install DHCP reset script
  copy: src=dhcpd-reset dest=/usr/local/bin mode=755

- name: start DCHP service
  service: name=isc-dhcp-server enabled=yes state=started
