- name: copy aeon-ztps conf file
  template: src=aeonztp.conf dest=/etc/aeonztp.conf owner=root group=root mode=644

- name: create aeonztp directories
  file: path={{ item }} state=directory owner={{ AeonUser }} group={{ AeonGroup }} mode=755
  with_items:
    - "{{ InstallDir }}/logs"
    - "{{ InstallDir }}/run"
    - /var/log/aeon-ztp
    - /var/run/aeon-ztp

- name: copy aeon-ztps webapp files over
  copy: src="{{ TopDir }}/webapp" dest={{ InstallDir }}
        owner={{ AeonUser }} group={{ AeonGroup }} mode=775 directory_mode=775

- name: copy aeon-ztps directories over
  synchronize: src="{{ TopDir }}/{{ item }}" dest={{ InstallDir }}
               rsync_opts="-avO --chown aeon:users" rsync_path="sudo rsync"
  with_items:
    - bin
    - etc
    - vendor_images
    - downloads

- nmae: make directories group writable
  command: chmod -R g+w {{ item }}
  with_items:
    - vendor_images
    - downloads

- name: Copy ztp-scripts to tftpboot
  copy: src="{{ TopDir }}/ztp-scripts/" dest={{ InstallDir }}/tftpboot owner=nobody mode=777

- name: symlink ztp-cumulus in downloads directory
  file: state=link
    src={{ InstallDir }}/tftpboot/ztp-cumulus.sh
    dest={{ InstallDir }}/downloads/ztp-cumulus.sh