- name: update hostname
  hostname: name={{ Hostname }}

#- name: update hostname in /etc/hosts
#  command: sed -i 's/^127.0.1.1[ \t]*ubuntu$/127.0.1.1\t{{ Hostname }}/' /etc/hosts

- include: users.yml
- include: apt_update.yml
- include: software.yml
- include: interfaces.yml
