- name: create interface cfg files
  template: src=iface.jinja2 dest=/etc/network/interfaces.d/{{ item.key }}.cfg
  with_dict: "{{ interfaces }}"

- name: restarting network interfaces
  service: name=networking state=restarted