---
- hosts: all
  become: yes
  vars:
    dnsmasq_site: http://www.thekelleys.org.uk/dnsmasq
    dnsmasq_ver: dnsmasq-2.75

  tasks:
    - name: Update apt-get cache
      apt: update_cache=yes

# --------------------------------------------------------
    - name: Create the 'admin' group
      group: name=admin state=present

    - name: Add 'admin' user
      user: 
        name: admin
        state: present
        groups: admin
        shell: /bin/bash
        password:
            $6$rounds=656000$2jNVVCliDs5XvmZs$eZ4F0WO6d6w5cBoMZ341hbuknOjx3ObhPHcgSR0D76gICz/Cc9IzXcPGaWzMdpiT7Cp.sflfiPhRDROvNH0eF/

    - name: add 'admin' to sudoers
      copy: src=etc/sudoers-10-admin dest=/etc/sudoers.d/10-admin mode=440

# --------------------------------------------------------
    - name: install the standard dnsmasq first ...
      apt: name=dnsmasq state=present 

    - name: disable dnsmasq
      service: name=dnsmasq state=stopped enabled=yes

    - name: Get dnsmasq specific version 
      get_url: url={{ dnsmasq_site }}/{{dnsmasq_ver}}.tar.gz dest=/tmp

    - name: Unpack dnsmasq
      unarchive: src=/tmp/{{ dnsmasq_ver }}.tar.gz dest=/tmp copy=no

    - name: Make dnsmasq
      shell: make install chdir=/tmp/{{ dnsmasq_ver}} 

    - name: replace dnsmasq
      file: state=link src=/usr/local/sbin/dnsmasq dest=/usr/sbin/dnsmasq force=yes

    - name: Setup dnsmasq config
      copy: src=etc/dnsmasq.conf dest=/etc/dnsmasq.conf

    - name: Install DNS reset script
      copy: src=bin/dns-reset dest=/usr/local/bin mode=755

# --------------------------------------------------------
    - name: Install DHCP server
      apt: name=isc-dhcp-server state=present

    - name: Install DHCP configuration file
      copy: src=etc/dhcpd.conf dest=/etc/dhcp/dhcpd.conf

    - name: touch an empty l3se-dhcp.conf file
      file: state=touch path=/etc/dhcp/l3se-dhcp.conf mode=666

    - name: Install DHCP default options file
      copy: src=default/isc-dhcp-server dest=/etc/default/isc-dhcp-server

    - name: Install DHCP reset script
      copy: src=bin/dhcpd-reset dest=/usr/local/bin mode=755

    - name: Create DHCP/DNS directories
      file: state=directory path=/etc/dhcp/{{item}} mode=777
      with_items:
        - scripts
        - hosts

    - name: Install DHCP/DNS trigger scripts
      copy: src=etc/add_dhcp_host.sh dest=/etc/dhcp/scripts mode=755

# --------------------------------------------------------
    - name: Install HTTP server
      apt: name=lighttpd state=present

    - name: Install HTTP files
      copy: src=www dest=/var owner=admin group=admin

# --------------------------------------------------------
    - name: Install TFTP server
      apt: name={{ item }} state=present
      with_items:
        - xinetd
        - tftpd
        - tftp

    - name: Install TFTP server config file
      copy: src=etc/tftp dest=/etc/xinetd.d mode=644 owner=root group=root

    - name: Install /tftpboot directory and contents
      copy: src=tftpboot dest=/ owner=nobody mode=777

# --------------------------------------------------------
    - name: Install tcpdump utility
      apt: name=tcpdump state=present

# --------------------------------------------------------
    - name: Install /etc/network/interfaces
      copy: src=etc/interfaces dest=/etc/network/interfaces

    - name: Install /etc/hosts
      copy: src=etc/hosts dest=/etc/hosts mode=644 owner=root group=root


