---
- hosts: all
  become: yes
  vars_files:
    - install_vars.yml

  tasks:
# --------------------------------------------------------
    - name: Create the 'admin' group
      group: name=admin state=present
    
    - name: Create the 'aeon' group
      group: name=aeon state=present

    - name: Create 'aeon' user
      user:
        name: aeon
        state: present
        groups: aeon,adm,admin
        shell: /bin/bash
        password:  $1$salty$Tv5XtH7LPxoZNyCJ3Z7r0/

    - name: Add 'admin' user
      user: 
        name: admin
        state: present
        groups: admin
        shell: /bin/bash
        password:
            $6$rounds=656000$2jNVVCliDs5XvmZs$eZ4F0WO6d6w5cBoMZ341hbuknOjx3ObhPHcgSR0D76gICz/Cc9IzXcPGaWzMdpiT7Cp.sflfiPhRDROvNH0eF/

    - name: add 'admin' to sudoers
      copy: src=sudoers-10-admin dest=/etc/sudoers.d/10-admin mode=440

    - name: add 'aeon' to sudoers
      copy: src=sudoers-20-aeon dest=/etc/sudoers.d/20-aeon mode=440

    - name: Install /etc/network/interfaces
      template: src=interfaces dest=/etc/network/interfaces

# --------------------------------------------------------
    - name: Update Linux apt-get cache
      apt: update_cache=yes

    - name: Install Linux packages
      apt: name={{ item }} state=present
      with_items:
        - build-essential
        - python-dev
        - python-pip
        - libxml2-dev
        - libxslt-dev
        - zlib1g-dev
        - rabbitmq-server
        - postgresql
        - postgresql-contrib
        - xinetd
        - tftpd
        - tftp
        - libfcgi
        - nginx-full
        - uwsgi
        - uwsgi-emperor
        - uwsgi-plugin-python
        - rsync

    - name: Install Ansible
      pip: name=ansible version=1.9.2

    - copy: src=../requirements.txt dest=/tmp/requirements.txt
    - name: Install python packages (pip)
      pip: requirements=/tmp/requirements.txt

# --------------------------------------------------------
    - include: filepaths.yml
    - include: install_tftpd.yml
    - include: install_dhcpd.yml
    - include: install_nginx.yml
    - include: install_uwsgi.yml
    - include: install_celery.yml
